name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '24 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install --no-input csvkit
    - name: Fetch latest data
      run: |-
        bash scrape.sh
    - name: Convert to csv
      run: |-
        in2csv data.xlsx > data_raw.csv
        bash sort.sh data_raw.csv > data.csv
        rm data_raw.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
